### ISSUE TITLE
Why so huge binary?

### ISSUE THREAD

**Issue by necros2k7** [devedse/DeveImageOptimizerWPF#4]
subj

**Comment by devedse** [comment]
@necros2k7 , the reason the size of the binary is so huge is because I basically pack all DLL's into one binary using this command:
```
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true
```

The `-r win-x64` also means that the whole dotnet core framework is included as well in this binary. I do this because not everyone has dotnet core installed on their system and I don't want my chocolatey package to have any dependencies besides FileOptimizerFull 😄 .

Did you already make use of my program? And if so what was your experience?
